//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Asteroid.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public class Asteroid extends FieldElement {
	/** */
	private int layers;
	
	/** */
	private boolean perihelion;
	
	/** */
	private Substance core;
	
	/** */
	private FieldElement neighbours;
	
	/** */
	public void AddNeighbour(FieldElement fi) {
	}
	
	/** */
	public void Asteroid() {
	}
	
	/** */
	public Substance GetCore() {
	}
	
	/** */
	public void SetCore(Substance s) {
	}
	
	/** */
	public void Explode() {
	}
	
	/** */
	public boolean IsPerihelion() {
	}
	
	/** */
	public Asteroid Add(Entity e) {
	}
	
	/** */
	public FieldElement GetRandomNeighbour() {
	}
	
	/** */
	public void Drilled() {
	}
	
	/** */
	public boolean CheckBase() {
	}
	
	/** */
	public void RemoveNeighbour(FieldElement fe) {
	}
	
	/** */
	public Asteroid Add(Entity e) {
	}
	
	/** */
	public void RemoveNeighbour(FieldElement fe) {
	}
}
