//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : BillOfSubstances.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public class BillOfSubstances {
	/** */
	private Substance bill;
	
	/** */
	private Substance toBeDeleted;
	
	/** */
	public boolean CheckBill(Substance s) {
	}
	
	/** */
	public Substance[0..*] GetToBeDeleted() {
	}
}
