//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Entity.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public abstract class Entity {
	/** */
	private Asteroid asteroid;
	
	/** */
	private Substance inventory;
	
	/** */
	public boolean Drill() {
	}
	
	/** */
	public abstract boolean Move();
	
	/** */
	public void Die() {
	}
	
	/** */
	public abstract void Explode();
	
	/** */
	public void SetAsteroid(Asteroid a) {
	}
	
	/** */
	public boolean Hide() {
	}
	
	/** */
	public void RemoveSubstance(Substance s) {
	}
	
	/** */
	public void AddSubstance(Substance s) {
	}
	
	/** */
	public Substance[0..*] GetInventory() {
	}
}
