//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Field.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public class Field {
	/** */
	private int untilStorm;
	
	/** */
	private BillOfSubstances baseBill;
	
	/** */
	private BillOfSubstances robotBill;
	
	/** */
	private BillOfSubstances portalBill;
	
	/** */
	private Settler settlers;
	
	/** */
	private Robot robots;
	
	/** */
	private FieldElement fieldElements;
	
	/** */
	public void StartGame(int playerCount) {
	}
	
	/** */
	public void Lose() {
	}
	
	/** */
	public void RemoveSettler(Settler s) {
	}
	
	/** */
	public void RemoveRobot(Robot r) {
	}
	
	/** */
	public void AddRobot(Object r: Robot) {
	}
	
	/** */
	public void Win() {
	}
	
	/** */
	public BillOfSubstances GetPortalBill() {
	}
	
	/** */
	public BillOfSubstances GetRobotBill() {
	}
	
	/** */
	public BillOfSubstances GetBaseBill() {
	}
	
	/** */
	public void AddFieldElement(FieldElement fe) {
	}
	
	/** */
	public void RemoveFieldElement(FieldElement fe) {
	}
}
