//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : FieldElement.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public abstract class FieldElement {
	/** */
	private Entity entities;
	
	/** */
	public abstract Asteroid Add(Entity e);
	
	/** */
	public abstract void RemoveNeighbour(FieldElement fe);
	
	/** */
	public void RemoveEntity(Entity e) {
	}
	
	/** */
	public void SunStorm() {
	}
}
