//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Ice.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public class Ice extends Substance {
	/** */
	public void Exposed() {
	}
	
	/** */
	public void Exposed() {
	}
}
