//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Portal.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public class Portal extends FieldElement {
	/** */
	private boolean activated;
	
	/** */
	private Asteroid pairedAsteroid;
	
	/** */
	public void Teleport(Entity e) {
	}
	
	/** */
	public void Portal() {
	}
	
	/** */
	public void RemoveNeighbour(FieldElement fe) {
	}
	
	/** */
	public Asteroid Add(Entity e) {
	}
	
	/** */
	public void SetPair(Portal p) {
	}
	
	/** */
	public void PairExploded() {
	}
	
	/** */
	public void SetAsteroid(Asteroid a) {
	}
	
	/** */
	public void Activate() {
	}
	
	/** */
	public Asteroid Add(Entity e) {
	}
	
	/** */
	public void RemoveNeighbour(FieldElement fe) {
	}
}
