//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Robot.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public class Robot extends Entity {
	/** */
	public boolean Move() {
	}
	
	/** */
	public void Robot(Asteroid asteroid) {
	}
	
	/** */
	public void Explode() {
	}
	
	/** */
	public boolean Move() {
	}
	
	/** */
	public void Explode() {
	}
}
