//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Settler.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public class Settler extends Entity {
	/** */
	private FieldElement selectedDestination;
	
	/** */
	private Portal portals;
	
	/** */
	public boolean Move() {
	}
	
	/** */
	public void Settler() {
	}
	
	/** */
	public boolean Mine() {
	}
	
	/** */
	public void Explode() {
	}
	
	/** */
	public void Store(Substance s) {
	}
	
	/** */
	public void BuildRobot() {
	}
	
	/** */
	public void BuildPortal() {
	}
	
	/** */
	public void BuildBase() {
	}
	
	/** */
	public void PlacePortal() {
	}
	
	/** */
	public Substance GetInventoryElement(int index) {
	}
	
	/** */
	public void AddPortal(Portal p) {
	}
	
	/** */
	public void RemovePortal(Portal p) {
	}
	
	/** */
	public boolean Move() {
	}
	
	/** */
	public void Explode() {
	}
}
