//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : Substance.java
//  @ Date : 18/03/2021
//  @ Author : Virtual Destructor
//
//




/** */
public abstract class Substance {
	/** */
	private Asteroid asteroid;
	
	/** */
	public abstract void Exposed();
	
	/** */
	public void Substance() {
	}
}
